import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

import { Card } from '../../ui/card/card';
import { Button } from '../../ui/button/button';
import { InputComponent } from '../../ui/input/input';
import { ProcurementService } from '../../core/services/procurement.service';
import { FormDraftService } from '../../core/services/form-draft.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-procurement-request',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    Card,
    Button,
    InputComponent
  ],
  templateUrl: './procurement-request.html',
  styleUrls: ['./procurement-request.css']
})
export class ProcurementRequest implements OnInit {
  private draftKey = 'procurement_request';

  procurement = {
    requestNumber: 'PR-AutoGenerated',
    requestTitle: '',
    departmentName: 'IT Department',
    requestedBy: '',
    itemName: '',
    productCategory: 'IT Equipment',
    quantity: 1,
    unit: 'Units',
    estimatedBudget: null as number | null,
    requiredDeliveryDate: '',
    priority: 'Medium',
    businessJustification: '',
    additionalRemarks: '',
    supportingDocument: '',
    requestStatus: 'Pending'
  };

  formError = '';
  isSubmitting = false;

  constructor(
    private router: Router,
    private procurementService: ProcurementService,
    private draftService: FormDraftService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    const user: any = this.authService.getCurrentUser();
    if (user) {
      this.procurement.requestedBy = user.name || user.email;
    }

    const saved = this.draftService.getDraft<any>(this.draftKey);
    if (saved) {
      this.procurement = { ...this.procurement, ...saved };
    }
  }

  saveDraftAuto(): void {
    this.draftService.saveDraft(this.draftKey, this.procurement);
  }

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.procurement.supportingDocument = input.files[0].name;
      this.saveDraftAuto();
    }
  }

  validateForm(): boolean {
    this.formError = '';
    const p = this.procurement;

    if (!p.requestTitle || !p.departmentName || !p.requestedBy || !p.itemName || !p.productCategory || !p.unit || !p.requiredDeliveryDate || !p.businessJustification) {
      this.formError = 'Please fill out all mandatory fields.';
      return false;
    }

    if (!p.quantity || p.quantity <= 0) {
      this.formError = 'Quantity must be greater than zero.';
      return false;
    }

    if (p.estimatedBudget === null || p.estimatedBudget <= 0 || isNaN(Number(p.estimatedBudget))) {
      this.formError = 'Estimated budget must be a positive numeric value.';
      return false;
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const selectedDate = new Date(p.requiredDeliveryDate);
    if (isNaN(selectedDate.getTime()) || selectedDate < today) {
      this.formError = 'Required Delivery Date cannot be in the past.';
      return false;
    }

    return true;
  }

  submitRequest(): void {
    if (!this.validateForm()) {
      return;
    }

    this.isSubmitting = true;
    const payload = {
      ...this.procurement,
      requestStatus: 'Pending'
    };

    this.procurementService.createProcurementRequest(payload).subscribe({
      next: (res) => {
        this.isSubmitting = false;
        this.draftService.clearDraft(this.draftKey);
        alert(`Procurement Request ${res.request_number || 'Submitted'} Successfully!`);
        this.router.navigate(['/procurement/requests']);
      },
      error: (err) => {
        this.isSubmitting = false;
        this.formError = err.error?.detail || 'Could not submit procurement request. Please try again.';
      }
    });
  }

  saveDraft(): void {
    this.saveDraftAuto();
    const payload = {
      ...this.procurement,
      requestStatus: 'Draft'
    };

    this.procurementService.createProcurementRequest(payload).subscribe({
      next: (res) => {
        alert(`Draft saved successfully as ${res.request_number || 'Draft'}!`);
        this.router.navigate(['/procurement/requests']);
      },
      error: () => {
        alert('Draft saved locally in browser.');
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/procurement-dashboard']);
  }
}