import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

import { Card } from '../../ui/card/card';
import { Button } from '../../ui/button/button';
import { InputComponent } from '../../ui/input/input';
import { ProcurementService } from '../../core/services/procurement.service';
import { FormDraftService } from '../../core/services/form-draft.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-procurement-request',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    Card,
    Button,
    InputComponent
  ],
  templateUrl: './procurement-request.html',
  styleUrls: ['./procurement-request.css']
})
export class ProcurementRequest implements OnInit {
  private draftKey = 'procurement_request';
  procurement = {
    requestNumber: 'PR-AutoGenerated',
    requestTitle: '',
    departmentName: 'IT Department',
    requestedBy: '',
    itemName: '',
    productCategory: 'IT Equipment',
    quantity: 1,
    unit: 'Units',
    estimatedBudget: null as number | null,
    requiredDeliveryDate: '',
    priority: 'Medium',
    businessJustification: '',
    additionalRemarks: '',
    supportingDocument: '',
    requestStatus: 'Pending'
  };
  formError = '';
  isSubmitting = false;
}

const PLACEHOLDER_PROCUREMENT_REQUEST_ROWS = [
  { id: 1, name: 'Northwind Steel', status: 'Active' },
  { id: 2, name: 'Orbit IT Systems', status: 'Pending Approval' },
  { id: 3, name: 'Delta Logistics', status: 'Under Review' },
  { id: 4, name: 'Ashcroft Maintenance', status: 'Inactive' },
  { id: 5, name: 'Harborline Equipment', status: 'Active' },
  { id: 6, name: 'Vertex Services', status: 'Pending Approval' },
  { id: 7, name: 'Ironvale Supplies', status: 'Under Review' },
  { id: 8, name: 'Copperfield Freight', status: 'Inactive' },
];

function usePlaceholderProcurementRequest(rows: any[]): any[] {
  return rows && rows.length ? rows : PLACEHOLDER_PROCUREMENT_REQUEST_ROWS;
}
