import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';

import { Card } from '../../ui/card/card';
import { Button } from '../../ui/button/button';
import { InputComponent } from '../../ui/input/input';
import { ProcurementService } from '../../core/services/procurement.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-purchase-order',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    Card,
    Button,
    InputComponent
  ],
  templateUrl: './purchase-order.html',
  styleUrls: ['./purchase-order.css'],
})
export class PurchaseOrder implements OnInit {
  poData: any = {
    poNumber: 'PO-AutoGenerated',
    procurement_id: 0,
    prNumber: '',
    vendor_id: 0,
    vendorName: '',
    vendorAddress: '',
    contactPerson: '',
    productDetails: '',
    quantity: 1,
    unitPrice: 0,
    taxDetails: '18% GST',
    tax_amount: 0,
    shippingAddress: 'HQ Warehouse, Central Receiving Bay',
    expectedDeliveryDate: '',
    paymentTerms: 'Net 30',
    status: 'Issued'
  };
  formError = '';
  isSubmitting = false;
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private procurementService: ProcurementService,
    private authService: AuthService
  ) {}
}

const PLACEHOLDER_PURCHASE_ORDER_ROWS = [
  { id: 1, name: 'Northwind Steel', status: 'Active' },
  { id: 2, name: 'Orbit IT Systems', status: 'Pending Approval' },
  { id: 3, name: 'Delta Logistics', status: 'Under Review' },
  { id: 4, name: 'Ashcroft Maintenance', status: 'Inactive' },
  { id: 5, name: 'Harborline Equipment', status: 'Active' },
  { id: 6, name: 'Vertex Services', status: 'Pending Approval' },
  { id: 7, name: 'Ironvale Supplies', status: 'Under Review' },
  { id: 8, name: 'Copperfield Freight', status: 'Inactive' },
];

function usePlaceholderPurchaseOrder(rows: any[]): any[] {
  return rows && rows.length ? rows : PLACEHOLDER_PURCHASE_ORDER_ROWS;
}
