import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';

import { Card } from '../../ui/card/card';
import { Button } from '../../ui/button/button';
import { InputComponent } from '../../ui/input/input';
import { ProcurementService } from '../../core/services/procurement.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-purchase-order',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    Card,
    Button,
    InputComponent
  ],
  templateUrl: './purchase-order.html',
  styleUrls: ['./purchase-order.css'],
})
export class PurchaseOrder implements OnInit {
  poData: any = {
    poNumber: 'PO-AutoGenerated',
    procurement_id: 0,
    prNumber: '',
    vendor_id: 0,
    vendorName: '',
    vendorAddress: '',
    contactPerson: '',
    productDetails: '',
    quantity: 1,
    unitPrice: 0,
    taxDetails: '18% GST',
    tax_amount: 0,
    shippingAddress: 'HQ Warehouse, Central Receiving Bay',
    expectedDeliveryDate: '',
    paymentTerms: 'Net 30',
    status: 'Issued'
  };

  formError = '';
  isSubmitting = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private procurementService: ProcurementService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    const prId = this.route.snapshot.queryParamMap.get('pr');
    const vendorId = this.route.snapshot.queryParamMap.get('vendor');

    if (prId) {
      this.poData.procurement_id = Number(prId);
      this.poData.prNumber = `PR-${prId}`;
      this.procurementService.getProcurementRequestById(prId).subscribe({
        next: (res) => {
          this.poData.productDetails = res.item_name;
          this.poData.quantity = res.quantity;
          this.poData.unitPrice = res.unit_price;
          if (res.expected_delivery_date) {
            this.poData.expectedDeliveryDate = res.expected_delivery_date.slice(0, 10);
          }
          if (res.vendor_id && !vendorId) {
            this.loadVendor(res.vendor_id);
          }
        }
      });
    }

    if (vendorId) {
      this.poData.vendor_id = Number(vendorId);
      this.loadVendor(Number(vendorId));
    }
  }

  loadVendor(vId: number): void {
    this.procurementService.getApprovedVendors().subscribe({
      next: (vendors) => {
        const v = vendors.find((item: any) => item.id === vId);
        if (v) {
          this.poData.vendor_id = v.id;
          this.poData.vendorName = v.company_name || v.vendor_name;
          this.poData.contactPerson = v.contact_person || v.vendor_name;
          this.poData.vendorAddress = v.address_line1 || 'Registered Vendor Facility';
        }
      }
    });
  }

  get totalCost(): number {
    const subtotal = (this.poData.quantity || 0) * (this.poData.unitPrice || 0);
    const tax = Number(this.poData.tax_amount || 0);
    return subtotal + tax;
  }

  validateForm(): boolean {
    this.formError = '';
    if (!this.poData.procurement_id || !this.poData.vendor_id) {
      this.formError = 'Procurement Request and Vendor must be selected.';
      return false;
    }
    if (!this.poData.expectedDeliveryDate) {
      this.formError = 'Expected Delivery Date is required.';
      return false;
    }
    return true;
  }

  generatePO(): void {
    if (!this.validateForm()) return;

    this.isSubmitting = true;
    const currentUser: any = this.authService.getCurrentUser();

    const payload = {
      procurement_id: Number(this.poData.procurement_id),
      vendor_id: Number(this.poData.vendor_id),
      vendor_name: this.poData.vendorName,
      vendor_address: this.poData.vendorAddress,
      contact_person: this.poData.contactPerson,
      item_name: this.poData.productDetails,
      quantity: Number(this.poData.quantity),
      unit_price: Number(this.poData.unitPrice),
      tax_amount: Number(this.poData.tax_amount || 0),
      shipping_address: this.poData.shippingAddress,
      expected_delivery_date: this.poData.expectedDeliveryDate,
      payment_terms: this.poData.paymentTerms,
      approved_by: currentUser?.name || 'Procurement Manager'
    };

    this.procurementService.createPurchaseOrder(payload).subscribe({
      next: (poRes) => {
        this.isSubmitting = false;
        alert(`Purchase Order ${poRes.po_number} generated successfully!`);
        this.router.navigate([`/procurement/purchase-order/${poRes.id}`]);
      },
      error: (err) => {
        this.isSubmitting = false;
        this.formError = err.error?.detail || 'Failed to generate Purchase Order. Please try again.';
      }
    });
  }

  saveDraft(): void {
    alert('Purchase Order draft saved.');
  }

  cancel(): void {
    this.router.navigate(['/procurement/requests']);
  }
}
