import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';

import { Card } from '../../ui/card/card';
import { Button } from '../../ui/button/button';
import { InputComponent } from '../../ui/input/input';
import { ProcurementService } from '../../core/services/procurement.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-purchase-order',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    Card,
    Button,
    InputComponent
  ],
  templateUrl: './purchase-order.html',
  styleUrls: ['./purchase-order.css'],
})
export class PurchaseOrder implements OnInit {
  poData: any = {
    poNumber: 'PO-AutoGenerated',
    procurement_id: 0,
    prNumber: '',
    vendor_id: 0,
    vendorName: '',
    vendorAddress: '',
    contactPerson: '',
    productDetails: '',
    quantity: 1,
    unitPrice: 0,
    taxDetails: '18% GST',
    tax_amount: 0,
    shippingAddress: 'HQ Warehouse, Central Receiving Bay',
    expectedDeliveryDate: '',
    paymentTerms: 'Net 30',
    status: 'Issued'
  };
  formError = '';
  isSubmitting = false;
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private procurementService: ProcurementService,
    private authService: AuthService
  ) {}
  ngOnInit(): void {
    const prId = this.route.snapshot.queryParamMap.get('pr');
    const vendorId = this.route.snapshot.queryParamMap.get('vendor');

    if (prId) {
      this.poData.procurement_id = Number(prId);
      this.poData.prNumber = `PR-${prId}`;
      this.procurementService.getProcurementRequestById(prId).subscribe({
        next: (res) => {
          this.poData.productDetails = res.item_name;
          this.poData.quantity = res.quantity;
          this.poData.unitPrice = res.unit_price;
          if (res.expected_delivery_date) {
            this.poData.expectedDeliveryDate = res.expected_delivery_date.slice(0, 10);
          }
          if (res.vendor_id && !vendorId) {
            this.loadVendor(res.vendor_id);
          }
        }
      });
    }

    if (vendorId) {
      this.poData.vendor_id = Number(vendorId);
      this.loadVendor(Number(vendorId));
    }
  }
  loadVendor(vId: number): void {
    this.procurementService.getApprovedVendors().subscribe({
      next: (vendors) => {
        const v = vendors.find((item: any) => item.id === vId);
        if (v) {
          this.poData.vendor_id = v.id;
          this.poData.vendorName = v.company_name || v.vendor_name;
          this.poData.contactPerson = v.contact_person || v.vendor_name;
          this.poData.vendorAddress = v.address_line1 || 'Registered Vendor Facility';
        }
      }
    });
  }
  get totalCost(): number {
    const subtotal = (this.poData.quantity || 0) * (this.poData.unitPrice || 0);
    const tax = Number(this.poData.tax_amount || 0);
    return subtotal + tax;
  }
}

const PLACEHOLDER_PURCHASE_ORDER_ROWS = [
  { id: 1, name: 'Orbit IT Systems', status: 'Pending Approval' },
  { id: 2, name: 'Delta Logistics', status: 'Under Review' },
  { id: 3, name: 'Ashcroft Maintenance', status: 'Inactive' },
  { id: 4, name: 'Harborline Equipment', status: 'Active' },
  { id: 5, name: 'Vertex Services', status: 'Pending Approval' },
  { id: 6, name: 'Ironvale Supplies', status: 'Under Review' },
  { id: 7, name: 'Copperfield Freight', status: 'Inactive' },
  { id: 8, name: 'Northwind Steel', status: 'Active' },
];

function usePlaceholderPurchaseOrder(rows: any[]): any[] {
  if (!rows || !rows.length) {
    return PLACEHOLDER_PURCHASE_ORDER_ROWS;
  }
  return rows.filter((row) => !!row);
}
